import InvLimDiss.SL.Framing.Basic
import InvLimDiss.SL.Framing.Defs
import InvLimDiss.SL.Framing.VarApprox
import InvLimDiss.SL.Classical
import InvLimDiss.SL.ClassicalProofrules
import InvLimDiss.SL.Entailment
import InvLimDiss.SL.Fuzzy
import InvLimDiss.SL.FuzzyProofrules
import InvLimDiss.SL.FuzzySubstSimp
